<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Phone number is too long</name>
   <tag></tag>
   <elementGuidId>cd70f113-8aa3-4678-8d98-d39a80044030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'error-mob' and (text() = 'Phone number is too long' or . = 'Phone number is too long')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-mob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#error-mob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b46c9bba-2fe2-44bb-ba02-50c14c1ea646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-alert alert-danger col-md-12 animated fadeInDown</value>
      <webElementGuid>5b3a25cb-9c8b-47bf-8c58-28b97961c43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-mob</value>
      <webElementGuid>9994c908-473b-4100-9499-d3f46bdcf75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number is too long</value>
      <webElementGuid>a81cdb81-ea1c-412a-99c4-84bcbcc0aa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-mob&quot;)</value>
      <webElementGuid>8febd433-65ff-43ff-8f88-508fde08133d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-mob']</value>
      <webElementGuid>d405619f-eb6a-440b-b808-9214cd2a7521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[2]/div/div</value>
      <webElementGuid>81e312d1-c2a8-4657-b471-1f5db0272472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[5]</value>
      <webElementGuid>756446d8-6688-438a-bb2e-a01518796815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::div[15]</value>
      <webElementGuid>f10363bf-4c93-458c-a369-fd811cb0ba56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/preceding::div[17]</value>
      <webElementGuid>a90db105-4359-4a88-848e-df8b3c026bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Phone number is too long']/parent::*</value>
      <webElementGuid>0657b0cc-c228-4e83-af89-ca4b988b7480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>1adcd522-f1e6-40bb-9bba-406411768b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-mob' and (text() = 'Phone number is too long' or . = 'Phone number is too long')]</value>
      <webElementGuid>8369a2a4-fbe6-46d0-a5ca-dc421a684fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
